/***********************************************************
 * Class: APICalloutsUtility
 * Description : utility class to hold all the constant variables necessary to perform callouts
 * Created on: 15-August-2022
 * Author: Bhuvaneshwari R
 * *********************************************************/
public class APICalloutsUtility {
    
    public static String NAMEDCREDENTIAL_TWILIOSERVICE='callout:Twilio_Creds/';
    public static String HEADER_AUTHORIZATION='Authorization';
    public static String ACCEPTTYPE='Accept';
    public static String CONTENTTYPE_JSON='application/json';
    public static Integer MAX_TIMEOUT=120000;

}